name: Practical Applications (Carpenter's or Woodcarver's Tools
type: feat
img: icons/tools/hand/chisel-steel-brown.webp
system:
  type:
    value: class
    subtype: ''
  description:
    value: >-
      <p>You may treat and adjust any weapons or armor made of wood over a short
      rest, causing them to deal +1 damage or grant +1 armor class. This does
      not stack with similar bonuses from the Smith follower. Furthermore, armor
      made of wood that was crafted or treated by you reduces the severity of
      its Flaw; on a natural 1 on a Dexterity saving throw or being critically
      hit the item only becomes damaged, not broken, unless already damaged.</p>
    chat: ''
  source:
    book: Heroes Old and New
    license: OGL 1.0a
  properties: []
  requirements: ''
  recharge:
    value: null
    charged: true
  activation:
    type: null
  uses:
    per: null
    max: null
effects: []
flags: {}
folder: null
_id: 8wfj6dksgi7qk0ec
_stats:
  coreVersion: '12'
  systemId: a5e
  systemVersion: 0.19.17
_key: '!items!8wfj6dksgi7qk0ec'
