name: Practical Applications (Weaver's Tools)
type: feat
img: icons/tools/hand/spinning-wheel-brown.webp
system:
  type:
    value: class
    subtype: ''
  description:
    value: >-
      <p>You may adjust the packs, satchels, and bags of a creature over a short
      rest, granting the creature an additional 20lbs carry weight and letting
      them carry an additional 2 days worth of Supply.</p>
    chat: ''
  source:
    book: Heroes Old and New
    license: OGL 1.0a
  properties: []
  requirements: ''
  recharge:
    value: null
    charged: true
  activation:
    type: null
  uses:
    per: null
    max: null
effects: []
flags: {}
folder: null
_id: 2xo87wt5ksh251we
_key: '!items!2xo87wt5ksh251we'
