name: Practical Applications
type: feat
img: icons/tools/hand/hammer-simple-stone.webp
system:
  type:
    value: class
    subtype: ''
  description:
    value: >-
      <p>At 7th level, you gain a special benefit based on your chosen tool. You
      must actually have and be able to use these tools to apply any of the
      following.</p><p>[insert links to the specific compendium items]</p>
    chat: ''
  source:
    book: Heroes Old and New
    license: OGL 1.0a
  properties: []
  requirements: ''
  recharge:
    value: null
    charged: true
  activation:
    type: null
  uses:
    per: null
    max: null
effects: []
flags: {}
folder: null
_id: 4a8gjnwr2tyt5vxj
_stats:
  coreVersion: '12'
  systemId: a5e
  systemVersion: 0.19.17
_key: '!items!4a8gjnwr2tyt5vxj'
